apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: azure-arc-sample
spec:
  releaseName: arc-k8s-demo
  chart:
    git: https://github.com/ahmedsza/azurearcpublic
    ref: main
    path: charts/weather
  values:
    serviceName: arc-k8s-demo